# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'
use_frameworks!

target 'TVShows' do
  pod 'Alamofire'
  pod 'SVProgressHUD'
  pod 'CodableAlamofire'
  pod 'Kingfisher', '~> 5.0'
  pod 'TBEmptyDataSet', '~> 3.0'

end
